version: '2'
services:
  spotify-spectrum:
    image: amcolash/spotify-spectrum
    build: ./
    container_name: spotify-spectrum
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/usr/src/app/data/
    network_mode: 'host'
    entrypoint: node /usr/src/app/spotify.js
    env_file:
      - .env
